name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  lint:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}m

      - name: Helm Lint
        run: helm lint ${{ env.CHART_DIR }}

  build:
    runs-on: arc-runner-set
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Helm Package
        run: |
          helm package "${{ env.CHART_DIR }}" --destination ./
          mv $(ls *.tgz) "${{ env.CHART_PACKAGE_NAME }}"
          echo "Chart package renamed to: ${{ env.CHART_PACKAGE_NAME }}"
          echo "Files in the current directory:"
          ls -l
        env:
          CHART_PACKAGE_NAME: "${{ env.CHART_NAME }}-${{ github.ref_name }}.tgz"
          CHART_DIR: "./my-app"
          CHART_NAME: "my-app"

  publish:
    runs-on: arc-runner-set
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Publish to GitHub Pages
        run: |
          git fetch
          git switch -C gh-pages
          mv ${{ env.CHART_PACKAGE_NAME }} ./charts/
          git add ./charts/${{ env.CHART_PACKAGE_NAME }}
          git commit -m "Publish Helm chart"
          git push origin gh-pages

  deploy:
    runs-on: arc-runner-set
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.CHART_NAME }} ./charts/${{ env.CHART_PACKAGE_NAME }} --namespace ${{ env.KUBE_NAMESPACE }}
        env:
          KUBE_NAMESPACE: "default"
          CHART_NAME: "my-app"
          CHART_PACKAGE_NAME: "${{ env.CHART_NAME }}-${{ github.ref_name }}.tgz"

