name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

env:
  HELM_VERSION: v3.15.3
  CHART_DIR: "./my-app"
  CHART_NAME: "my-app"
  KUBE_NAMESPACE: "default"

jobs:
  lint:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build:
    runs-on: arc-runner-set
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Helm Package
        run: |
          helm package "${{ env.CHART_DIR }}" --destination ./
          mv $(ls *.tgz) "${{ env.CHART_NAME }}-${{ github.ref_name }}.tgz"
          echo "Chart package renamed to: ${{ env.CHART_NAME }}-${{ github.ref_name }}.tgz"
          echo "Files in the current directory:"
          ls -l

  publish:
    runs-on: arc-runner-set
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Configure Git
        run: |
          git config user.name "Stas"
          git config user.email "levon7299@gmail.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  deploy:
    runs-on: arc-runner-set
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ env.CHART_NAME }} ./charts/${{ env.CHART_NAME }}-${{ github.ref_name }}.tgz --namespace ${{ env.KUBE_NAMESPACE }}

